# Generated by Django 3.2.7 on 2022-05-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig_app', '0002_auto_20220513_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.ImageField(upload_to='images'),
        ),
    ]
