# Generated by Django 3.2.7 on 2022-06-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig_app', '0003_alter_post_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='uploaded_pic', to='ig_app.User'),
        ),
    ]
