# Generated by Django 3.2.7 on 2022-06-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig_app', '0005_auto_20220611_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, to='ig_app.User'),
        ),
    ]
